oVirt/ovirt-release

- .github/workflows/check-patch.yml
Adding GitHub action for checking incoming patches.
> Add check-patch action

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/request-for-enhancement.md
- .github/pull_request_template.md
Adding templates for issues and PRs
> Add templates from oVirt/gerrit-to-gh

- .github/workflows/check-patch.yml
* Extend automation to 4.4 branches
[y/n] yes
> automation: add 4.4 branches automation

- .gitignore
- CODEOWNERS
- LICENSE-2.0.txt
- LICENSE.md
- Makefile.am
- configure.ac
- gpl-2.0.txt
- host-node/Makefile.am
- host-node/cockpit/branding/branding.css
- host-node/systemd/system-preset/98-ovirt-host-node.preset
- lgpl-2.1.txt
- ovirt-release-master.spec.in
* added CODEOWNERS
* added missing license files
* included license files in built archives
[y/n] yes
> Align with oVirt/gerrit-to-gh

- .copr/Makefile
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/request-for-enhancement.md
- .github/pull_request_template.md
- .github/workflows/check-patch.yml
- .gitignore
- README.md
* Cherry-picked and adapted the needed patches to enable COPR integration for ovirt-4.4 branch
[y/n] yes
> Add copr build to ovirt-4.4 branch

- .github/workflows/repoclosure.yml
* run repoclosure hourly in EMEA timezone working hours.
[y/n] yes
> automation: run repoclosure

- .github/workflows/repoclosure.yml
Fixed syntax error in repoclosure error reporting
[y/n] y
> Fixed syntax error

- .github/workflows/repoclosure.yml
Fixes issue #19 
* Fixes errors left in previous PR
* Use dnf consistently
[y/n] yes
> automation: fix repoclosure test

- .github/workflows/repoclosure.yml
Fixes issue #21
* Fix dnf command line.
[y/n] yes
> repoclosure: fix missing -y to dnf install command

- README.md
* Add a badge to quickly see if repoclosure is broken.
[y/n] yes
> README: add repository closure badge

- README.md
* Add monitoring table for the whole project.
[y/n] yes
> monitoring: single dashboard for build status

- configure.ac
- ovirt-release-master.spec.in
- ovirt-snapshot.repo.in
* This PR is based/depends on PR#25
* Dropping ovirt-master* repositories provided by resources.ovirt.org as we migrated to COPR.
[y/n] yes
> Drop resources snapshot repositories

- configure.ac
- ovirt-release44.spec.in
* build: ovirt-release44-4.4.9.2
[y/n] yes
> build: ovirt-release44-4.4.9.2

- .github/workflows/check-patch.yml
- .github/workflows/repoclosure.yml
* Set permissions for workflow after 2FA enforcing change
[y/n] yes
> workflow: set permissions

- README.md
* Adding a few more projects which migrated to GitHub.
[y/n] yes
> README: add a few more projects

- README.md
* Add 2 more projects which migrated to GitHub
[y/n] yes
> README: add 2 more projects

- ovirt-release-master.spec.in
* When rebuilding a src.rpm for testing purposes without this change you'll have to update version and release in 3 places. With this change you need to change only once.
[y/n] yes
> packaging: spec: use version and release macro

- .github/workflows/repoclosure.yml
* Re-submitting PR #35 as it seems that PR is missing a field needed by CI to properly run.
[y/n] yes
> Redo close repoclosure issue on success

- node-optional.el9.repo
* Updated node-optional.el9.repo with CentOS Stream 9 provided repo files.
[y/n] yes
> el9: node-optional: align with centos repo files

- configure.ac
- ovirt-release44.spec.in
* Bump to 4.4.9.3 for rebuilding oVirt Node.
[y/n] yes
> build: ovirt-release44-4.4.9.3

- README.md
* Added a few more project migrated to GitHub
[y/n] yes
> README: add more project migrated to GitHub

- README.md
* README: add a few more projects migrated to GitHub
[y/n] yes
> README: add a few more projects migrated to GitHub

- ovirt-release-master.spec.in
* Enable powertools repo also on @rocky-linux.
[y/n] yes
> Enable powertools on Rocky

- .github/workflows/repoclosure-44.yml
* Add repository closure test for oVirt 4.4
[y/n] yes
> Automation: oVirt 4.4 repoclosure

- ovirt-release44.spec.in
Fixes issue #45
* Backporting PR #43 to 4.4 branch
[y/n] yes
> [4.4] Enable powertools on Rocky

- README.md
Change-Id: I73752342417ec397a672f505454387b6ea7ebbeb
Signed-off-by: Yedidyah Bar David <didi@redhat.com>
Fixes issue # (delete if not relevant)
*
*
*
[y/n]
> Add cockpit-ovirt

- .github/workflows/check-patch.yml
* Check patch workflow diverged for ovirt-4.4 branch
[y]
> automation: Modify check patch to only install ovirt-4.4 release

- .copr/Makefile
> build: ovirt-release44-4.4.10_rc2

- .copr/Makefile
> build: post ovirt-release44-4.4.10_rc2

- .github/workflows/check-patch.yml
* switch to oVirt/upload-rpms-action for archiving rpms.
[y/n] yes
> automation: use oVirt/upload-rpms-action

- .github/workflows/repoclosure.yml
Fixes issue #78
* We removed the imageio and ioprocess preview repos but forgot to update automation about it.
[y/n] yes
> automation: fix repoclosure job

- .github/workflows/check-patch.yml
The upload action was updated to differentiate between distro for artifacts.
> Use newer upload action

- .github/workflows/check-patch.yml
- ovirt-snapshot.repo.in
* Add ovirt-appliance repo
[y/n] yes
> repos: add ovirt-appliance repo

- .github/workflows/repoclosure-44.yml
* In PR#93 repository names have been aligned to CentOS Stream shipped repos. Adjusting the job to match the changes.
[y/n] yes
> repoclosure-44: adjust to PR#93

- ovirt-snapshot.repo.in
*  add oVirt Node updates repo
[y/n] yes
> repos: add oVirt Node updates repo

- .github/workflows/repoclosure.yml
* preparing repoclosure test for upcoming alpha release
[y/n] yes
> automation: preparing for alpha release

- .github/workflows/repoclosure.yml
* adapt reclosure to upcoming 4.5 alpha
[y/n] yes
> repoclosure: adapt to 4.5 alpha upcoming

- configure.ac
* moving contact for the package to devel mailing list as infra is not maintaining this package.
[y/n] yes
> configure: set contact to devel

- configure.ac
- ovirt-release-host-node.spec.in
- ovirt-release45.spec.in
* build: ovirt-release-host-node-4.5.0
[y/n] y
> build: ovirt-release-host-node-4.5.0

- .github/workflows/repoclosure-45.yml
* test released content only for 4.5
* not consuming alma and rocky yet as 8.6 is not yet available.
[y/n] yes
> automation: add 4.5 repoclosure job

- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
we use ansible-test in ovirt-ansible-collection
> filter out ansible-test from yoga too

- .github/workflows/check-patch.yml
- .github/workflows/repoclosure-44.yml
- .github/workflows/repoclosure-45.yml
- .github/workflows/repoclosure.yml
Fixes issue #155
- use dnf consistently
- fix yamllint reported issues
- drop el9 workaround for sha1 signature as copr now use stronger hashing
- run distro-sync to get updated containers
[y/n] y
> automation: update actions

- .github/workflows/repoclosure.yml
- ovirt-el8-ppc64le-deps.repo.in
- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
- ovirt-el8-x86_64-deps.repo.in
- ovirt-el9-stream-aarch64-deps.repo.in
- ovirt-el9-stream-ppc64le-deps.repo.in
- ovirt-el9-stream-x86_64-deps.repo.in
* master is now zed, moving to yoga repos
[y/n] y
> rdo: move from master to yoga

- .github/workflows/repoclosure-45.yml
- .github/workflows/repoclosure.yml
* yoga is being pushed to centos stream mirors, adapting to it.
[y/n] y
> 4.5: adapt to el8 yoga release repos

- configure.ac
- ovirt-release-host-node.spec.in
* Prepare for oVirt 4.5.0 GA node build
[y/n] yes
> build: bump for 4.5.0 GA

- .github/workflows/repoclosure-45.yml
* Align with centos-release-ovirt45-9.0-3
[y/n] y
> 4.5: el9: switch to released yoga

- .github/workflows/repoclosure-45.yml
* Align with centos-release-ovirt45-9.0-4
[y/n] y
> 4.5: el9: use centos released yoga

- AUTHORS
- CODEOWNERS
- Makefile.am
- ovirt-el8-ppc64le-deps.repo.in
- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
- ovirt-el8-x86_64-deps.repo.in
- ovirt-el9-stream-aarch64-deps.repo.in
- ovirt-el9-stream-ppc64le-deps.repo.in
- ovirt-el9-stream-x86_64-deps.repo.in
- ovirt-release-host-node.spec.in
- ovirt-release45.spec.in
Backport PR #195
* aligned codeowners
* aligned authors
* aligned source code location
* aligned yoga repositories
[y/n] y
> Backport PR #195 - Align with current status

- configure.ac
- ovirt-release-host-node.spec.in
*  bump for 4.5.0.2 async
[y/n] y
> build: bump for 4.5.0.2 async

- .github/workflows/repoclosure.yml
Fixes issue #254
* dnf copr on el9 is now working same way as el8.
y
> el9: copr changed behavior

- configure.ac
* Bump version to 4.5.4-0.0
[y]
> Bump version to 4.5.4-0.0

- ovirt-el8-ppc64le-deps.repo.in
- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
- ovirt-el8-x86_64-deps.repo.in
* Backported and re-ordered OVS/OVN package excludes
[y]
> Backport rdo ovn ovs excludes

- ovirt-el8-ppc64le-deps.repo.in
- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
- ovirt-el8-x86_64-deps.repo.in
* Re-ordered OVS/OVN package excludes
[y]
> el8: Reordered OVS/OVN package name excludes by ABC

- configure.ac
- ovirt-release-host-node.spec.in
* Bump for Async release 4.5.3.1
[y]
> build: 4.5.3.1 Async

- configure.ac
- ovirt-release-host-node.spec.in
> Bump ovirt release host node 4.5.4 GA

- .github/workflows/check-patch.yml
* Mark cloned git repository as safe
y
> automation: mark git repo as safe

- configure.ac
- ovirt-release-host-node.spec.in
- ovirt-release-master.spec.in
> Bump to 4.5.5

- ovirt-el8-ppc64le-deps.repo.in
- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
- ovirt-el8-x86_64-deps.repo.in
- ovirt-el9-stream-aarch64-deps.repo.in
- ovirt-el9-stream-ppc64le-deps.repo.in
- ovirt-el9-stream-x86_64-deps.repo.in
Fixes issue #282 
add rdo-network-scripts-openvswitch to excludes
> Fixes #282 add rdo-network-scripts-openvswitch to excludes

- README.md
* Removed already released milestones and added the new ones.
y
> Add upcoming release milestones

- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
- ovirt-el9-stream-aarch64-deps.repo.in
- ovirt-el9-stream-ppc64le-deps.repo.in
- ovirt-el9-stream-x86_64-deps.repo.in
* filter out ansible-test from yoga too
* exlude openstack's custom ansible version
y
> openstack ansible

- .github/workflows/repoclosure-45.yml
* manually enable jaxb:4 module for satisfying missing deps.
y
> enable jaxb:4 on rocky and alma

- .github/workflows/check-patch.yml
- configure.ac
- ovirt-el8-ppc64le-deps.repo.in
- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
- ovirt-el8-x86_64-deps.repo.in
- ovirt-el9-stream-aarch64-deps.repo.in
- ovirt-el9-stream-ppc64le-deps.repo.in
- ovirt-el9-stream-x86_64-deps.repo.in
- ovirt-release-host-node.spec.in
> build: 4.5.5 GA

- configure.ac
- ovirt-release-host-node.spec.in
- ovirt-release-master.spec.in
> Bump to 4.5.6

- .github/workflows/repoclosure-45.yml
- .github/workflows/repoclosure.yml
* Run repoclosure once a week
y
> Run repoclosure once a week

- Makefile.am
- configure.ac
- node-optional.el10.repo
- ovirt-el10-stream-aarch64-deps.repo.in
- ovirt-el10-stream-ppc64le-deps.repo.in
- ovirt-el10-stream-s390x-deps.repo.in
- ovirt-el10-stream-x86_64-deps.repo.in
- ovirt-release-master.spec.in
* Enable ovirt-release-master to handle CentOS Stream 10, so development on that platform can start.
y
> Add CentOS Stream 10 repos
