oVirt/ovirt-release

- ovirt-el8-ppc64le-deps.repo.in
- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
- ovirt-el8-x86_64-deps.repo.in
Moving oVirt 4.5 repo on CentOS Build System to module hotfix.
It contains ant packages which are filtered out by modularity otherwise.
> el8stream: CBS oVirt 4.5 module hotfix

- .github/workflows/repoclosure.yml
This PR fixes a bug when a second failure is discovered on the repoclosure job.
[y/n] Yes
> Fixed commenting on second failure

- ovirt-el8-ppc64le-deps.repo.in
- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
- ovirt-el8-x86_64-deps.repo.in
* Dropping a personal COPR repo used up to now due to missing packages in officiall repositories.
Required packages for building and installing oVirt are now included either in oVirt branded COPR
or in CentOS Virtualization SIG.
[y/n] yes
> Drop sbonazzo:EL8_collection COPR repo

- ovirt-el9-stream-aarch64-deps.repo.in
- ovirt-el9-stream-x86_64-deps.repo.in
needed packages should be shipped via Virt SIG.
> el9: repos: drop EL9 collection in favor of Virt SIG

- .github/workflows/repoclosure.yml
This PR fixes the inverted condition on repoclosure success reporting.
[y/n] Yes
> Fixed repoclosure success reporting

- node-optional.el8.repo
- node-optional.el9.repo
Allowing to install ipa-client on oVirt Node as it's not installed by default anymore
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2017681
> node: make ipa-client available as optional

- README.md
Following projects moved to github:
* ovirt-engine-extension-aaa-ldap
* ovirt-engine-extension-aaa-misc
* ovirt-engine-extension-logger-log4j
* ovirt-jboss-modules-maven-plugin
> README: add a few more projects migrated to GitHub

- .github/workflows/repoclosure-44.yml
* Switching to 4.4-pre for rocky as it will require an ovirt-release44 release to fix the missing repo.
[y/n] yes
> repoclosure-44: address rocky linux failure

- ovirt-release44.spec.in
Previously the node-optional.repo was installing only on GA releases.
This patch fixes that, so it will be installed in other cases as well.
RHBZ#2036795
Fixes issue # (delete if not relevant)
* node-optional.repo file is now installed in /etc/yum.repos.d/ directory for pre-GA releases as well.
[y]
> packaging: Fixed the node-optional.repo issue

- .github/workflows/check-patch.yml
Previously we used unified check patch for both master and ovirt-4.4
branches, and tried to guess which version of ovirt-release we need
to install. This patch diverges the check patch for master branch.
* Diverges check patch for the master branch
[y]
> automation: Modify check patch to only install master release

- ovirt-el8-stream-x86_64-deps.repo.in
- ovirt-el8-x86_64-deps.repo.in
- ovirt-el9-stream-aarch64-deps.repo.in
- ovirt-el9-stream-x86_64-deps.repo.in
Fixes issue #78
* ioprocess and imageio are now built in copr within ovirt copr repo. Avoiding to provide them in multiple places as it ends up with breaking repository closure.
[y/n] yes
> Drop preview repos for ioprocess and imageio

- node-optional.el8.repo
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2017681
* Add missing deps for ipa-client on oVirt Node el8
[y/n] yes
> node-optional.el8: add missing deps for ipa-client

- .github/workflows/check-patch.yml
- ovirt-el8-ppc64le-deps.repo.in
- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
- ovirt-el8-x86_64-deps.repo.in
Fixes issue #91
* CentOS Linux 8 repos are going to be archived to the vault and it won't be possible to update them anymore.
Preparing to switch to the repos provided for CentOS Stream also for Rocky and Alma.
[y/n] yes
> repos: switch to centos stream

- node-optional.el9.repo
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2017681
* add missing deps for ipa-client on oVirt Node based on CentOS Stream 9
[y/n] yes
> node-optional.el9: add missing deps for ipa-client

- .copr/Makefile
- .github/workflows/check-patch.yml
- LICENSE.md
- Makefile.am
- configure.ac
- ovirt-release-host-node.spec.in
- ovirt-release-master.spec.in
splitting ovirt-release-host-node out of ovirt-release-master packaging
because in order to build oVirt Node on CentOS CBS we need the node
related rpms but we don't need the ovirt-release-master rpm itself.
This also allow us to build ovirt-release-master ad noarch and
ovirt-release-host-node as arch specific solving the build issue that
leads to have missing EFI related packages within oVirt Node.
[y/n] yes
> packaging: split ovirt-release-host-node

- .github/workflows/repoclosure.yml
* Check the repoclosure of the repositories enabled via centos-release-ovirt45 for CentOS Virtualization SIG. This is used for building oVirt Node on CBS.
[y/n] yes
> repoclosure: check centos-release-ovirt45 for el8

- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
Advanced virtualization is now included in AppStream: removing from needed repos for CentOS Stream.
> el8-stream: drop advanced virtualization

- .github/workflows/repoclosure.yml
dropping advanced-virtualization repos from repoclosure as it has been
dropped from the needed repositories afte qemu-kvm 6.2 landed in CentOS
Stream 8.
[y/n] yes
> automation: drop advanced-virtualization

- node-optional.el8.repo
- node-optional.el9.repo
It has been decided to close wontfix BZ#2017681
so reverting the requirement to move ipa-client from mandatory to
optional.
The SCAP guide will be fixed for not requiring ipa-client to be absent
on the system.
[y/n] yes
> revert the move of ipa-client to node-optional

- .github/workflows/check-patch.yml
- .github/workflows/repoclosure.yml
Fixes issue #117
recent openssl dropped support for sha1 algo but COPR and several
other packaging systems are still signing RPMS with sha1.
In order to be able to install RPMs switching from default crypto policy
to legacy one untill RPMS with newer sha signature will be provided.
This requires [crypto-policies-20220223-1.git5203b41.el9](https://kojihub.stream.centos.org/koji/buildinfo?buildID=17332) which is not yet
on c9s mirrors but should land there soon.
[y/n] yes
> automation: use legacy crypto policy on el9

- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
yoga testing is shipping python-sqlalchemy which is newer than the one
shipped in CentOS Stream under modularity filtering.
Setting module_hotfixes for yoga repo for overriding the filtering.
[y/n] yes
> yoga: set module_hotfixes

- ovirt-release-host-node.spec.in
- ovirt-release-master.spec.in
moved node repos config to ovirt-release-host-node to ensure it works
even when ovirt-release rpm is not installed.
This is needed in order to be able to use centos-release-ovirt45 rpm
instead.
[y/n] yes
> [master] decouple node and release rpms

- ovirt-release-host-node.spec.in
- ovirt-release45.spec.in
Moved node repos config to ovirt-release-host-node to ensure it works even when ovirt-release rpm is not installed.
This is needed in order to be able to use centos-release-ovirt45 rpm instead.
[y/n] yes
> decouple node and release rpms

- configure.ac
* bumping version to 4.5.1 to be able to distinguish between master and 4.5 builds for oVirt Node.
[y/n] yes
> build: post 4.5 branching

- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
Use CentOS Stream 9 opstools repository instead of CentOS 8 repository
for oVirt release master and 4.5
> Use CentOS Stream 8 opstools repository

- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
we use ansible-test in ovirt-ansible-collection
Fixes issue # (delete if not relevant)
*
*
*
[y/n]
> filter out ansible-test from yoga too

- .github/workflows/repoclosure-45.yml
- .github/workflows/repoclosure.yml
Fixes issue #152
Using official `centos-gluster10` repo id instead of the custom
`ovirt-45-centos-stream-gluster10` id which we provided as workaround for
the missing release rpm on el8.
[y/n] y
> automation: use centos-gluster10 on el8

- ovirt-release-host-node.spec.in
Fixes issue #145
This reverts commit 22fbbb961c577c3ee022424f8580df917c77fdaa.
New glusterr-ansible-roles are compatible with ansible-core 2.12
[y/n] y
> Revert "node: Remove gluster-ansible-roles"

- ovirt-release-host-node.spec.in
* Now that gluster-ansible-roles supports ansible-core 2.12 adding it to el9 build too
[y/n] y
> el9: include gluster-ansible-roles within node el9

- .github/workflows/check-patch.yml
- .github/workflows/repoclosure-45.yml
- .github/workflows/repoclosure.yml
ovirt-engine >= 4.5.0 requires enabling mod_auth_openidc module due to
dependency on mod_auth_openidc package required for KeyCloak integration
as mentioned in https://bugzilla.redhat.com/2021497
> oVirt Engine 4.5 requires enabling mod_auth_openidc

- .github/workflows/check-patch.yml
- .github/workflows/repoclosure-45.yml
- .github/workflows/repoclosure.yml
ovirt-engine >= 4.5.0 requires enabling mod_auth_openidc module due to
dependency on mod_auth_openidc package required for KeyCloak integration
as mentioned in https://bugzilla.redhat.com/2021497
(cherry picked from commit cfb74c849b37ecb60f0f331536981cf1264cd38f)
> [4.5] oVirt Engine 4.5 requires enabling mod_auth_openidc

- .copr/Makefile
Backport #191 to 4.5 branch
See CVE-2022-24765
git >= 2.35.2 won't work on copr make_srpm builds without marking
the working directory as a safe.directory in git.
[y/n] y
> [4.5] mark the copr make_srpm git dir as safe

- .github/workflows/repoclosure-45.yml
Fixes issue #238
* rockylinux/latest seems not available anymore after Rocky Linux 9 GA.
y
> repoclosure-45: use rockylinux/8

- ovirt-release-host-node.spec.in
Use of find is a lot more reliable way to search for files, than
using a simple glob, especially for the case when no files matching
the glob exist.
* Use find utility instead of a simple glob for searching.
[y]
> host-node: Use find instead of a simple glob

- ovirt-el8-ppc64le-deps.repo.in
- ovirt-el8-stream-ppc64le-deps.repo.in
- ovirt-el8-stream-x86_64-deps.repo.in
- ovirt-el8-x86_64-deps.repo.in
To prevent any conflict exclude OvS and OVN packages from OpenStack.
> el8: Exclude the rdo OvS/OVN packages

- .github/workflows/repoclosure-45.yml
We have moved most of the package builds to CBS, but there are still a
few packages which cannot be built on CBS. So when running repoclosure
on resources.ovirt.org repo, we need to check only those packages which
cannot be built on CBS to workaround repoclosure limitation around
having different package versions on multiple repositories.
> Workaround repoclosure limitation for resources.ovirt.org

- configure.ac
- ovirt-release-host-node.spec.in
* Bump patch for ovirt-release-host-node 4.5.3.2 Async release
[y]
> build: 4.5.3.2 Async

- .github/workflows/check-patch.yml
- .github/workflows/repoclosure-45.yml
- .github/workflows/repoclosure.yml
* address Node.js 12 deprecation warning in GitHub actions execution
> Node.js 12 actions are deprecated.
> For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> Please update the following actions to use Node.js 16: actions/checkout@v2
y
> github: address Node.js 12 deprecation

- .github/workflows/check-patch.yml
* addresses:
> Node.js 12 actions are deprecated.
> For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> Please update the following actions to use Node.js 16: actions/upload-artifact@v2
y
> github: update to oVirt/upload-rpms-action@main

- ovirt-el9-stream-aarch64-deps.repo.in
- ovirt-el9-stream-ppc64le-deps.repo.in
- ovirt-el9-stream-x86_64-deps.repo.in
To prevent any conflicts exclude OvS and OVN packages
from OpenStack.
> el9: Exclude RDO OvS/OVN packages

- .github/workflows/check-patch.yml
- .github/workflows/repoclosure-45.yml
- .github/workflows/repoclosure.yml
* switch to `ovirt/checkout-action@main` within actions. Solves: `Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3.` warning.
y
> Update github actions
